### ISSUE TITLE
 How to use there is an installation tutorial

### ISSUE THREAD

**Issue by mc159963** [USBBios/Dream-qBot-Botnet-Source#2]
How to use there is an installation tutorial

**Comment by gizliag** [comment]
> How to use there is an installation tutorial

where is the training video i couldn't see it can you share the source?

**Comment by USBBios** [comment]
> How to use there is an installation tutorial

[https://github.com/USBBios/Dream-qBot-Botnet-Source/blob/main/TutQBOT.txt](url)
